name: Deploy to EC2 (IA PICHAU - 🇧🇷)

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Conectar ao servidor EC2 e fazer o deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            cd pichau
            git pull
            sudo docker system prune --all --volumes -f
            sudo docker-compose up --build -d